[SYMBOL_SECTION]
LOT_SIZE = 0.01
; As of 16 May 2025
; Based on my own self observation
; Then I self decide the best spread to put
; Able to accept decimal spread, follow cTrader
; If cTrader has 1 decimal, then only 1 decimal is accepted
SPREAD_XAUUSD = 6
SPREAD_DAXEUR = 6
SPREAD_NDXUSD = 4
SPREAD_DJIUSD = 4
SPREAD_NIKJPY = 8 # So far saw is 4.2, guess i put 8? i dk
; As of 14 May 2025
; How I got this:
;   Self calculate, see 1 pip is how much
;   changes in price
; 0.10 means 1 pip is price changes in 0.10
; Price: 3000 + 1pip = 3000.10
PRICE_PER_PIP_XAUUSD = 0.10
PRICE_PER_PIP_DAXEUR = 1.00
PRICE_PER_PIP_NDXUSD = 1.00
PRICE_PER_PIP_DJIUSD = 1.00
PRICE_PER_PIP_NIKJPY = 1.00
; As of 16 May 2025
; How I got this:
;   Self calculate, use demo acc, place 1 PENDING ORDER
;   At the script, put breakpoint where it retrieves pending order
;   Inspect res.order[0...1...2...].relativeStopLoss
; To set TP/SL
; OpenAPI use "Relative"
; 10,000 means 1 pip
; So if i want to set 30pips SL, my relative is 300,000
; How I calculate, take XAUUSD for example
; In cTrader, set 34.7 pips
; In coding, print out ProtoOAOrder.relativeStopLoss
; relativeStopLoss shows 347000
; 1pip = 10000
; It is found that, other symbols are different in value
RELATIVE_PER_PIP_XAUUSD = 10000
RELATIVE_PER_PIP_DAXEUR = 100000
RELATIVE_PER_PIP_NDXUSD = 100000
RELATIVE_PER_PIP_DJIUSD = 100000
RELATIVE_PER_PIP_NIKJPY = 100000
; As of 16 May 2025
; How I got this
;   Do ProtoOASymbolByIdReq & check minVolume and maxVolume
; MIN_LOT = 0.01 lot
; Take XAUUSD for example, 0.01 lot = 100 volume
MIN_LOT_XAUUSD = 100
MIN_LOT_DAXEUR = 10
MIN_LOT_NDXUSD = 10
MIN_LOT_DJIUSD = 10
MIN_LOT_NIKJPY = 1000
; So far, this is not used yet, i lazy to redesign the
; function that uses MIN_LOT_XAUUSD * 100 to get 100 lot
; I believe, as long as MIN_LOT not wrong, it less likely
; to get so wrong.
MAX_LOT_XAUUSD = 1000000
MAX_LOT_DAXEUR = 100000
MAX_LOT_NDXUSD = 100000
MAX_LOT_DJIUSD = 100000
MAX_LOT_NIKJPY = 10000000
; Expiry (time only) in millisecond from midnight (0000)
; Calculation, example 930pm, get today's date, then add
; 21h 30m of seconds to it.
; 21 hours = 60x60x21=75600
; 30 mins = 60x30=1800
; Total 77400 * 1000 = 77400000 milliseconds
; 22h30m, 1030pm, until US open
EXPIRY_STANDARD_DAXEUR = 81000000
; 29h   , 5am   , until US close
EXPIRY_STANDARD_XAUUSD = 104400000
EXPIRY_STANDARD_NDXUSD = 104400000
EXPIRY_STANDARD_DJIUSD = 104400000
; 21h30m, 930pm , until US open  (DST)
EXPIRY_DST_DAXEUR = 77400000
; 28h   , 4am   , until US close (DST)
EXPIRY_DST_XAUUSD = 100800000
EXPIRY_DST_NDXUSD = 100800000
EXPIRY_DST_DJIUSD = 100800000
; 22h30m, 1030pm, until US open
EXPIRY_STANDARD_DAXEUR_FRIDAY = 81000000
; 27h   , 3am   , early 2 hours until US close
EXPIRY_STANDARD_XAUUSD_FRIDAY = 97200000
EXPIRY_STANDARD_NDXUSD_FRIDAY = 97200000
EXPIRY_STANDARD_DJIUSD_FRIDAY = 97200000
; 21h30m, 930pm, until US open  (DST)
EXPIRY_DST_DAXEUR_FRIDAY = 77400000
; 26h   , 2am  , early 2 hours until US close (DST)
EXPIRY_DST_XAUUSD_FRIDAY = 93600000
EXPIRY_DST_NDXUSD_FRIDAY = 93600000
EXPIRY_DST_DJIUSD_FRIDAY = 93600000
; A way to get these all listed with `acc` command
; Is to go to cTrader app give permission
; openapi.ctrader.com/apps
; Click sandbox & you know what 7 im saying
A_6016088 = "GOLD SOHAI"
A_6020705 = "SND SOHAI"
A_6024342 = "SNR SOHAI"
A_1002719 = "Demo"
A_6025310 = "GOLD CONTEST"

